export var airlab = [

{
    "request": {
        "lang": "en",
        "currency": "USD",
        "time": 1,
        "id": "i6wf600ork8",
        "server": "l",
        "host": "airlabs.co",
        "pid": 2940692,
        "key": {
            "id": 22441,
            "api_key": "02615d93-395d-4ad0-883e-b99d81c413ba",
            "type": "free",
            "expired": null,
            "registered": "2023-02-06T16:35:53.000Z",
            "limits_by_hour": 2500,
            "limits_by_minute": 250,
            "limits_by_month": 1000,
            "limits_total": 994
        },
        "params": {
            "bbox": "29.563,33.760,33.321,36.002",
            "lang": "en"
        },
        "version": 9,
        "method": "flights",
        "client": {
            "ip": "2a10:8012:15:1700:e08c:2a67:f21c:8802",
            "geo": {},
            "connection": {},
            "device": {},
            "agent": {},
            "karma": {
                "is_blocked": false,
                "is_crawler": false,
                "is_bot": false,
                "is_friend": false,
                "is_regular": true
            }
        }
    },
    "response": [
        {
            "hex": "706065",
            "reg_number": "9K-AKN",
            "flag": "KW",
            "lat": 30.223526,
            "lng": 33.856255,
            "alt": 10668,
            "dir": 163,
            "speed": 490,
            "v_speed": 0,
            "squawk": "1645",
            "flight_number": "162",
            "flight_icao": "KAC162",
            "flight_iata": "KU162",
            "dep_icao": "LSGG",
            "dep_iata": "GVA",
            "arr_icao": "OKBK",
            "arr_iata": "KWI",
            "airline_icao": "KAC",
            "airline_iata": "KU",
            "aircraft_icao": "A20N",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "896318",
            "reg_number": "A6-ENV",
            "flag": "AE",
            "lat": 30.207048,
            "lng": 33.866566,
            "alt": 11277,
            "dir": 165,
            "speed": 498,
            "v_speed": 0,
            "squawk": "1605",
            "flight_number": "128",
            "flight_icao": "UAE54J",
            "flight_iata": "EK128",
            "dep_icao": "LOWW",
            "dep_iata": "VIE",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "8963E6",
            "reg_number": "A6-EOI",
            "flag": "AE",
            "lat": 29.880344,
            "lng": 34.066288,
            "alt": 12496,
            "dir": 151,
            "speed": 964,
            "v_speed": 0,
            "squawk": "3325",
            "flight_number": "50",
            "flight_icao": "UAE50",
            "flight_iata": "EK50",
            "dep_icao": "EDDM",
            "dep_iata": "MUC",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "A388",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "8963EA",
            "reg_number": "A6-EOM",
            "flag": "AE",
            "lat": 29.92067,
            "lng": 34.041676,
            "alt": 11887,
            "dir": 152,
            "speed": 931,
            "v_speed": 0,
            "squawk": "1613",
            "flight_number": "98",
            "flight_icao": "UAE32L",
            "flight_iata": "EK98",
            "dep_icao": "LIRF",
            "dep_iata": "FCO",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "A388",
            "updated": 1675702441,
            "status": "en-route"
        },
        {
            "hex": "3C656B",
            "reg_number": "D-AIKK",
            "flag": "DE",
            "lat": 29.78561,
            "lng": 34.523243,
            "alt": 11887,
            "dir": 148,
            "speed": 946,
            "v_speed": 0,
            "squawk": "1672",
            "flight_number": "630",
            "flight_icao": "DLH630",
            "flight_iata": "LH630",
            "dep_icao": "EDDF",
            "dep_iata": "FRA",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "DLH",
            "airline_iata": "LH",
            "aircraft_icao": "A333",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "394A00",
            "reg_number": "F-GSQA",
            "flag": "FR",
            "lat": 29.638227,
            "lng": 36.09219,
            "alt": 11285,
            "dir": 77,
            "speed": 1120,
            "v_speed": -1.3,
            "squawk": "0641",
            "flight_number": "662",
            "flight_icao": "AFR662",
            "flight_iata": "AF662",
            "dep_icao": "LFPG",
            "dep_iata": "CDG",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "AFR",
            "airline_iata": "AF",
            "aircraft_icao": "B77W",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "06A2E0",
            "reg_number": "A7-BFS",
            "flag": "QA",
            "lat": 29.705961,
            "lng": 36.445583,
            "alt": 10668,
            "dir": 77,
            "speed": 1076,
            "v_speed": -0.3,
            "squawk": "3333",
            "flight_number": "8445",
            "flight_icao": "QTR50U",
            "flight_iata": "QR8445",
            "dep_icao": "LIMC",
            "dep_iata": "MXP",
            "arr_icao": "OTHH",
            "arr_iata": "DOH",
            "airline_icao": "QTR",
            "airline_iata": "QR",
            "aircraft_icao": "B77L",
            "updated": 1675702441,
            "status": "en-route"
        },
        {
            "hex": "440395",
            "reg_number": "OE-IZO",
            "flag": "AT",
            "lat": 32.505844,
            "lng": 34.369438,
            "alt": 3581,
            "dir": 121,
            "speed": 633,
            "squawk": "7602",
            "flight_number": "5205",
            "flight_icao": "EJU5205",
            "flight_iata": "U25205",
            "dep_icao": "EDDB",
            "dep_iata": "BER",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "EJU",
            "airline_iata": "U2",
            "aircraft_icao": "A320",
            "updated": 1675702436,
            "status": "en-route"
        },
        {
            "hex": "500194",
            "reg_number": "T7-ASK",
            "flag": "SM",
            "lat": 32.015846,
            "lng": 34.896404,
            "alt": 0,
            "dir": 28,
            "speed": 42,
            "squawk": "7217",
            "flight_number": "821",
            "flight_icao": "SMF821",
            "flight_iata": "LY821",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "EBLG",
            "arr_iata": "LGG",
            "airline_icao": "SMF",
            "airline_iata": "LY",
            "aircraft_icao": "A306",
            "updated": 1675702442,
            "status": "en-route"
        },
        {
            "hex": "738058",
            "reg_number": "4X-EKU",
            "flag": "IL",
            "lat": 32.015652,
            "lng": 34.898575,
            "alt": 0,
            "dir": 247,
            "speed": 16,
            "squawk": "2254",
            "flight_number": "312",
            "flight_icao": "ELY312",
            "flight_iata": "LY312",
            "dep_icao": "EGGW",
            "dep_iata": "LTN",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "ELY",
            "airline_iata": "LY",
            "aircraft_icao": "B738",
            "updated": 1675701235,
            "status": "en-route"
        },
        {
            "hex": "01023E",
            "reg_number": "SU-BUV",
            "flag": "EG",
            "lat": 29.703306,
            "lng": 36.37891,
            "alt": 10043,
            "dir": 79,
            "speed": 1048,
            "squawk": "3355",
            "flight_number": "469",
            "flight_icao": "MSC469",
            "flight_iata": "SM469",
            "dep_icao": "HECA",
            "dep_iata": "CAI",
            "arr_icao": "OERK",
            "arr_iata": "RUH",
            "airline_icao": "MSC",
            "airline_iata": "SM",
            "aircraft_icao": "A320",
            "updated": 1675702435,
            "status": "en-route"
        },
        {
            "hex": "471F31",
            "reg_number": "HA-LVD",
            "flag": "HU",
            "lat": 32.035172,
            "lng": 34.911201,
            "alt": 190,
            "dir": 209,
            "speed": 225,
            "squawk": "7102",
            "flight_number": "2811",
            "flight_iata": "W62811",
            "dep_icao": "LOWW",
            "dep_iata": "VIE",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_iata": "W6",
            "aircraft_icao": "A21N",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "48AF01",
            "reg_number": "SP-LVB",
            "flag": "PL",
            "lat": 32.008701,
            "lng": 34.870674,
            "alt": 0,
            "dir": 225,
            "speed": 22,
            "squawk": "0000",
            "aircraft_icao": "B38M",
            "updated": 1675702408,
            "status": "en-route"
        },
        {
            "hex": "4B194A",
            "reg_number": "HB-JPA",
            "flag": "CH",
            "lat": 32.008633,
            "lng": 34.871628,
            "alt": 0,
            "dir": 30,
            "speed": 25,
            "squawk": "0000",
            "aircraft_icao": "A21N",
            "updated": 1675702415,
            "status": "en-route"
        },
        {
            "hex": "73806A",
            "reg_number": "4X-EKP",
            "flag": "IL",
            "lat": 32.008106,
            "lng": 34.874416,
            "alt": 0,
            "dir": 120,
            "speed": 22,
            "squawk": "0000",
            "aircraft_icao": "B738",
            "updated": 1675701938,
            "status": "en-route"
        },
        {
            "hex": "8960D8",
            "reg_number": "A6-EBQ",
            "flag": "AE",
            "lat": 29.645416,
            "lng": 36.128277,
            "alt": 10668,
            "dir": 77,
            "speed": 1079,
            "squawk": "1626",
            "flight_number": "748",
            "flight_icao": "UAE748",
            "flight_iata": "EK748",
            "dep_icao": "DTTA",
            "dep_iata": "TUN",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "89610C",
            "reg_number": "A6-ECE",
            "flag": "AE",
            "lat": 31.952728,
            "lng": 35.424042,
            "alt": 6050,
            "dir": 103,
            "speed": 881,
            "squawk": "0436",
            "flight_number": "932",
            "flight_icao": "UAE932",
            "flight_iata": "EK932",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702441,
            "status": "en-route"
        }
    ],
    "terms": "Unauthorized access is prohibited and punishable by law. \nReselling data 'As Is' without AirLabs.Co permission is strictly prohibited. \nFull terms on https://airlabs.co/. \nContact us info@airlabs.co"
}
]