export var airlab = [

{
    "request": {
        "lang": "en",
        "currency": "USD",
        "time": 1,
        "id": "i6wf600ork8",
        "server": "l",
        "host": "airlabs.co",
        "pid": 2940692,
        "key": {
            "id": 22441,
            "api_key": "02615d93-395d-4ad0-883e-b99d81c413ba",
            "type": "free",
            "expired": null,
            "registered": "2023-02-06T16:35:53.000Z",
            "limits_by_hour": 2500,
            "limits_by_minute": 250,
            "limits_by_month": 1000,
            "limits_total": 994
        },
        "params": {
            "bbox": "29.563,33.760,33.321,36.002",
            "lang": "en"
        },
        "version": 9,
        "method": "flights",
        "client": {
            "ip": "2a10:8012:15:1700:e08c:2a67:f21c:8802",
            "geo": {},
            "connection": {},
            "device": {},
            "agent": {},
            "karma": {
                "is_blocked": false,
                "is_crawler": false,
                "is_bot": false,
                "is_friend": false,
                "is_regular": true
            }
        }
    },
    "response": [
        {
            "hex": "706065",
            "reg_number": "9K-AKN",
            "flag": "KW",
            "lat": 30.223526,
            "lng": 33.856255,
            "alt": 10668,
            "dir": 163,
            "speed": 490,
            "v_speed": 0,
            "squawk": "1645",
            "flight_number": "162",
            "flight_icao": "KAC162",
            "flight_iata": "KU162",
            "dep_icao": "LSGG",
            "dep_iata": "GVA",
            "arr_icao": "OKBK",
            "arr_iata": "KWI",
            "airline_icao": "KAC",
            "airline_iata": "KU",
            "aircraft_icao": "A20N",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "896318",
            "reg_number": "A6-ENV",
            "flag": "AE",
            "lat": 30.207048,
            "lng": 33.866566,
            "alt": 11277,
            "dir": 165,
            "speed": 498,
            "v_speed": 0,
            "squawk": "1605",
            "flight_number": "128",
            "flight_icao": "UAE54J",
            "flight_iata": "EK128",
            "dep_icao": "LOWW",
            "dep_iata": "VIE",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "8963E6",
            "reg_number": "A6-EOI",
            "flag": "AE",
            "lat": 29.880344,
            "lng": 34.066288,
            "alt": 12496,
            "dir": 151,
            "speed": 964,
            "v_speed": 0,
            "squawk": "3325",
            "flight_number": "50",
            "flight_icao": "UAE50",
            "flight_iata": "EK50",
            "dep_icao": "EDDM",
            "dep_iata": "MUC",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "A388",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "8963EA",
            "reg_number": "A6-EOM",
            "flag": "AE",
            "lat": 29.92067,
            "lng": 34.041676,
            "alt": 11887,
            "dir": 152,
            "speed": 931,
            "v_speed": 0,
            "squawk": "1613",
            "flight_number": "98",
            "flight_icao": "UAE32L",
            "flight_iata": "EK98",
            "dep_icao": "LIRF",
            "dep_iata": "FCO",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "A388",
            "updated": 1675702441,
            "status": "en-route"
        },
        {
            "hex": "3C656B",
            "reg_number": "D-AIKK",
            "flag": "DE",
            "lat": 29.78561,
            "lng": 34.523243,
            "alt": 11887,
            "dir": 148,
            "speed": 946,
            "v_speed": 0,
            "squawk": "1672",
            "flight_number": "630",
            "flight_icao": "DLH630",
            "flight_iata": "LH630",
            "dep_icao": "EDDF",
            "dep_iata": "FRA",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "DLH",
            "airline_iata": "LH",
            "aircraft_icao": "A333",
            "updated": 1675702440,
            "status": "en-route"
        },
        {
            "hex": "394A00",
            "reg_number": "F-GSQA",
            "flag": "FR",
            "lat": 29.638227,
            "lng": 36.09219,
            "alt": 11285,
            "dir": 77,
            "speed": 1120,
            "v_speed": -1.3,
            "squawk": "0641",
            "flight_number": "662",
            "flight_icao": "AFR662",
            "flight_iata": "AF662",
            "dep_icao": "LFPG",
            "dep_iata": "CDG",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "AFR",
            "airline_iata": "AF",
            "aircraft_icao": "B77W",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "06A2E0",
            "reg_number": "A7-BFS",
            "flag": "QA",
            "lat": 29.705961,
            "lng": 36.445583,
            "alt": 10668,
            "dir": 77,
            "speed": 1076,
            "v_speed": -0.3,
            "squawk": "3333",
            "flight_number": "8445",
            "flight_icao": "QTR50U",
            "flight_iata": "QR8445",
            "dep_icao": "LIMC",
            "dep_iata": "MXP",
            "arr_icao": "OTHH",
            "arr_iata": "DOH",
            "airline_icao": "QTR",
            "airline_iata": "QR",
            "aircraft_icao": "B77L",
            "updated": 1675702441,
            "status": "en-route"
        },
        {
            "hex": "440395",
            "reg_number": "OE-IZO",
            "flag": "AT",
            "lat": 32.505844,
            "lng": 34.369438,
            "alt": 3581,
            "dir": 121,
            "speed": 633,
            "squawk": "7602",
            "flight_number": "5205",
            "flight_icao": "EJU5205",
            "flight_iata": "U25205",
            "dep_icao": "EDDB",
            "dep_iata": "BER",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "EJU",
            "airline_iata": "U2",
            "aircraft_icao": "A320",
            "updated": 1675702436,
            "status": "en-route"
        },
        {
            "hex": "500194",
            "reg_number": "T7-ASK",
            "flag": "SM",
            "lat": 32.015846,
            "lng": 34.896404,
            "alt": 0,
            "dir": 28,
            "speed": 42,
            "squawk": "7217",
            "flight_number": "821",
            "flight_icao": "SMF821",
            "flight_iata": "LY821",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "EBLG",
            "arr_iata": "LGG",
            "airline_icao": "SMF",
            "airline_iata": "LY",
            "aircraft_icao": "A306",
            "updated": 1675702442,
            "status": "en-route"
        },
        {
            "hex": "738058",
            "reg_number": "4X-EKU",
            "flag": "IL",
            "lat": 32.015652,
            "lng": 34.898575,
            "alt": 0,
            "dir": 247,
            "speed": 16,
            "squawk": "2254",
            "flight_number": "312",
            "flight_icao": "ELY312",
            "flight_iata": "LY312",
            "dep_icao": "EGGW",
            "dep_iata": "LTN",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "ELY",
            "airline_iata": "LY",
            "aircraft_icao": "B738",
            "updated": 1675701235,
            "status": "en-route"
        },
        {
            "hex": "01023E",
            "reg_number": "SU-BUV",
            "flag": "EG",
            "lat": 29.703306,
            "lng": 36.37891,
            "alt": 10043,
            "dir": 79,
            "speed": 1048,
            "squawk": "3355",
            "flight_number": "469",
            "flight_icao": "MSC469",
            "flight_iata": "SM469",
            "dep_icao": "HECA",
            "dep_iata": "CAI",
            "arr_icao": "OERK",
            "arr_iata": "RUH",
            "airline_icao": "MSC",
            "airline_iata": "SM",
            "aircraft_icao": "A320",
            "updated": 1675702435,
            "status": "en-route"
        },
        {
            "hex": "471F31",
            "reg_number": "HA-LVD",
            "flag": "HU",
            "lat": 32.035172,
            "lng": 34.911201,
            "alt": 190,
            "dir": 209,
            "speed": 225,
            "squawk": "7102",
            "flight_number": "2811",
            "flight_iata": "W62811",
            "dep_icao": "LOWW",
            "dep_iata": "VIE",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_iata": "W6",
            "aircraft_icao": "A21N",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "48AF01",
            "reg_number": "SP-LVB",
            "flag": "PL",
            "lat": 32.008701,
            "lng": 34.870674,
            "alt": 0,
            "dir": 225,
            "speed": 22,
            "squawk": "0000",
            "aircraft_icao": "B38M",
            "updated": 1675702408,
            "status": "en-route"
        },
        {
            "hex": "4B194A",
            "reg_number": "HB-JPA",
            "flag": "CH",
            "lat": 32.008633,
            "lng": 34.871628,
            "alt": 0,
            "dir": 30,
            "speed": 25,
            "squawk": "0000",
            "aircraft_icao": "A21N",
            "updated": 1675702415,
            "status": "en-route"
        },
        {
            "hex": "73806A",
            "reg_number": "4X-EKP",
            "flag": "IL",
            "lat": 32.008106,
            "lng": 34.874416,
            "alt": 0,
            "dir": 120,
            "speed": 22,
            "squawk": "0000",
            "aircraft_icao": "B738",
            "updated": 1675701938,
            "status": "en-route"
        },
        {
            "hex": "8960D8",
            "reg_number": "A6-EBQ",
            "flag": "AE",
            "lat": 29.645416,
            "lng": 36.128277,
            "alt": 10668,
            "dir": 77,
            "speed": 1079,
            "squawk": "1626",
            "flight_number": "748",
            "flight_icao": "UAE748",
            "flight_iata": "EK748",
            "dep_icao": "DTTA",
            "dep_iata": "TUN",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702443,
            "status": "en-route"
        },
        {
            "hex": "89610C",
            "reg_number": "A6-ECE",
            "flag": "AE",
            "lat": 31.952728,
            "lng": 35.424042,
            "alt": 6050,
            "dir": 103,
            "speed": 881,
            "squawk": "0436",
            "flight_number": "932",
            "flight_icao": "UAE932",
            "flight_iata": "EK932",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702441,
            "status": "en-route"
        },

        {
            "hex": "test",
            "reg_number": "A6-ECE",
            "flag": "AE",
            "lat": 32.061996,
            "lng": 34.77475,
            "alt": 700,
            "dir": 120,
            "speed": 881,
            "squawk": "0436",
            "flight_number": "932",
            "flight_icao": "UAE932",
            "flight_iata": "EK932",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "LLBG",
            "arr_iata": "DXB",
            "airline_icao": "UAE",
            "airline_iata": "EK",
            "aircraft_icao": "B77W",
            "updated": 1675702441,
            "status": "en-route"
        }
    ],
    "terms": "Unauthorized access is prohibited and punishable by law. \nReselling data 'As Is' without AirLabs.Co permission is strictly prohibited. \nFull terms on https://airlabs.co/. \nContact us info@airlabs.co"
}
]

export var airlab30 = [

{
    "request": {
        "lang": "en",
        "currency": "USD",
        "time": 1,
        "id": "nb4k9gfnqts",
        "server": "l",
        "host": "airlabs.co",
        "pid": 4110019,
        "key": {
            "id": 22441,
            "api_key": "02615d93-395d-4ad0-883e-b99d81c413ba",
            "type": "free",
            "expired": "2023-03-11T00:00:00.000Z",
            "registered": "2023-02-06T16:35:53.000Z",
            "limits_by_hour": 2500,
            "limits_by_minute": 250,
            "limits_by_month": 1000,
            "limits_total": 999
        },
        "params": {
            "bbox": "29.563,33.760,33.321,36.002",
            "lang": "en"
        },
        "version": 9,
        "method": "flights",
        "client": {
            "ip": "2a10:8012:15:1700:ecef:a275:86c4:d06c",
            "geo": {},
            "connection": {},
            "device": {},
            "agent": {},
            "karma": {
                "is_blocked": false,
                "is_crawler": false,
                "is_bot": false,
                "is_friend": false,
                "is_regular": true
            }
        }
    },
    "response": [
        {
            "hex": "39CF0D",
            "reg_number": "F-HTYN",
            "flag": "FR",
            "lat": 29.664001,
            "lng": 34.237572,
            "alt": 11894,
            "dir": 125,
            "speed": 1063,
            "v_speed": 0,
            "squawk": "1665",
            "flight_number": "226",
            "flight_icao": "AFR226",
            "flight_iata": "AF226",
            "dep_icao": "LFPG",
            "dep_iata": "CDG",
            "arr_icao": "VIDP",
            "arr_iata": "DEL",
            "airline_icao": "AFR",
            "airline_iata": "AF",
            "aircraft_icao": "A359",
            "updated": 1675952458,
            "status": "en-route"
        },
        {
            "hex": "7103D8",
            "reg_number": "HZ-AK42",
            "flag": "SA",
            "lat": 30.461626,
            "lng": 34.766293,
            "alt": 11277,
            "dir": 114,
            "speed": 992,
            "v_speed": 0,
            "squawk": "0421",
            "flight_number": "144",
            "flight_icao": "SVA144",
            "flight_iata": "SV144",
            "dep_icao": "LFPG",
            "dep_iata": "CDG",
            "arr_icao": "OERK",
            "arr_iata": "RUH",
            "airline_icao": "SVA",
            "airline_iata": "SV",
            "aircraft_icao": "B77W",
            "updated": 1675952449,
            "status": "en-route"
        },
        {
            "hex": "4D2237",
            "reg_number": "9H-QAQ",
            "flag": "IE",
            "lat": 32.415627,
            "lng": 34.523079,
            "alt": 11887,
            "dir": 119,
            "speed": 992,
            "v_speed": 0.3,
            "squawk": "1273",
            "flight_number": "9731",
            "flight_icao": "RYR9731",
            "flight_iata": "FR9731",
            "dep_icao": "LIRA",
            "dep_iata": "CIA",
            "arr_icao": "OJAQ",
            "arr_iata": "AQJ",
            "airline_icao": "RYR",
            "airline_iata": "FR",
            "aircraft_icao": "B738",
            "updated": 1675952460,
            "status": "en-route"
        },
        {
            "hex": "346385",
            "reg_number": "EC-NGN",
            "flag": "ES",
            "lat": 32.011871,
            "lng": 34.683014,
            "alt": 1638,
            "dir": 291,
            "speed": 500,
            "squawk": "4135",
            "flight_number": "1302",
            "flight_icao": "AEA1302",
            "flight_iata": "UX1302",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "LEMD",
            "arr_iata": "MAD",
            "airline_icao": "AEA",
            "airline_iata": "UX",
            "aircraft_icao": "B789",
            "updated": 1675952455,
            "status": "en-route"
        },
        {
            "hex": "440666",
            "reg_number": "OE-LBJ",
            "flag": "AT",
            "lat": 32.141434,
            "lng": 34.112659,
            "alt": 6035,
            "dir": 286,
            "speed": 588,
            "squawk": "5546",
            "flight_number": "858",
            "flight_icao": "AUA858G",
            "flight_iata": "OS858",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "LOWW",
            "arr_iata": "VIE",
            "airline_icao": "AUA",
            "airline_iata": "OS",
            "aircraft_icao": "A320",
            "updated": 1675952459,
            "status": "en-route"
        },
        {
            "hex": "738058",
            "reg_number": "4X-EKU",
            "flag": "IL",
            "lat": 31.955978,
            "lng": 34.990852,
            "alt": 533,
            "dir": 273,
            "speed": 301,
            "squawk": "4156",
            "flight_number": "2522",
            "flight_icao": "ELY2522",
            "flight_iata": "LY2522",
            "dep_icao": "LKPR",
            "dep_iata": "PRG",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "ELY",
            "airline_iata": "LY",
            "aircraft_icao": "B738",
            "updated": 1675952460,
            "status": "en-route"
        },
        {
            "hex": "738488",
            "reg_number": "4X-EMF",
            "flag": "IL",
            "lat": 30.400194,
            "lng": 35.13131,
            "alt": 4693,
            "dir": 190,
            "speed": 661,
            "squawk": "5041",
            "flight_number": "2825",
            "flight_icao": "AIZ2825",
            "flight_iata": "IZ2825",
            "airline_icao": "AIZ",
            "airline_iata": "IZ",
            "aircraft_icao": "E195",
            "updated": 1675952328,
            "status": "en-route"
        },
        {
            "hex": "740733",
            "reg_number": "JY-AYS",
            "flag": "JO",
            "lat": 31.587694,
            "lng": 36.051029,
            "alt": 3307,
            "dir": 123,
            "speed": 581,
            "squawk": "0000",
            "aircraft_icao": "A320",
            "updated": 1675952451,
            "status": "en-route"
        },
        {
            "hex": "15203C",
            "reg_number": "RA-73788",
            "flag": "RU",
            "lat": 29.732542,
            "lng": 34.117558,
            "alt": 9845,
            "dir": 333,
            "speed": 755,
            "squawk": "7342",
            "flight_number": "427",
            "flight_icao": "AFL427",
            "flight_iata": "SU427",
            "dep_icao": "HESH",
            "dep_iata": "SSH",
            "arr_icao": "UUEE",
            "arr_iata": "SVO",
            "airline_icao": "AFL",
            "airline_iata": "SU",
            "aircraft_icao": "A333",
            "updated": 1675952459,
            "status": "en-route"
        },
        {
            "hex": "3C64A7",
            "reg_number": "D-AIEG",
            "flag": "DE",
            "lat": 32.006538,
            "lng": 34.877487,
            "alt": 0,
            "dir": 120,
            "speed": 29,
            "squawk": "4367",
            "flight_number": "680",
            "flight_icao": "DLH680",
            "flight_iata": "LH680",
            "dep_icao": "EDDM",
            "dep_iata": "MUC",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "DLH",
            "airline_iata": "LH",
            "aircraft_icao": "A21N",
            "updated": 1675952425,
            "status": "en-route"
        },
        {
            "hex": "4BAA72",
            "reg_number": "TC-JSR",
            "flag": "TR",
            "lat": 32.138687,
            "lng": 34.869091,
            "alt": 1478,
            "dir": 129,
            "speed": 450,
            "squawk": "2377",
            "flight_number": "786",
            "flight_icao": "THY786",
            "flight_iata": "TK786",
            "dep_icao": "LTFM",
            "dep_iata": "IST",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "THY",
            "airline_iata": "TK",
            "aircraft_icao": "A321",
            "updated": 1675952460,
            "status": "en-route"
        },
        {
            "hex": "4C8087",
            "reg_number": "5B-DDL",
            "flag": "CY",
            "lat": 32.006035,
            "lng": 34.879311,
            "alt": 0,
            "dir": 36,
            "speed": 7,
            "squawk": "5561",
            "flight_number": "212",
            "flight_icao": "CYF212",
            "flight_iata": "U8212",
            "dep_icao": "LLBG",
            "dep_iata": "TLV",
            "arr_icao": "LGAV",
            "arr_iata": "ATH",
            "airline_icao": "CYF",
            "airline_iata": "U8",
            "aircraft_icao": "A320",
            "updated": 1675952417,
            "status": "en-route"
        },
        {
            "hex": "73806D",
            "reg_number": "4X-EKH",
            "flag": "IL",
            "lat": 32.002178,
            "lng": 34.873188,
            "alt": 0,
            "dir": 53,
            "speed": 0,
            "squawk": "0000",
            "aircraft_icao": "B738",
            "updated": 1675951755,
            "status": "landed"
        },
        {
            "hex": "73806E",
            "reg_number": "4X-EKJ",
            "flag": "IL",
            "lat": 32.049225,
            "lng": 34.993156,
            "alt": 1112,
            "dir": 127,
            "speed": 368,
            "squawk": "7616",
            "flight_number": "2372",
            "flight_icao": "ELY2372",
            "flight_iata": "LY2372",
            "dep_icao": "EDDB",
            "dep_iata": "BER",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "ELY",
            "airline_iata": "LY",
            "aircraft_icao": "B738",
            "updated": 1675952459,
            "status": "en-route"
        },
        {
            "hex": "8965B6",
            "reg_number": "A6-FMZ",
            "flag": "AE",
            "lat": 30.326157,
            "lng": 34.188213,
            "alt": 10668,
            "dir": 150,
            "speed": 877,
            "squawk": "1604",
            "flight_number": "1682",
            "flight_icao": "FDB1682",
            "flight_iata": "FZ1682",
            "dep_icao": "LIRN",
            "dep_iata": "NAP",
            "arr_icao": "OMDB",
            "arr_iata": "DXB",
            "airline_icao": "FDB",
            "airline_iata": "FZ",
            "aircraft_icao": "B38M",
            "updated": 1675952456,
            "status": "en-route"
        },
        {
            "hex": "A11BA0",
            "reg_number": "N17002",
            "flag": "US",
            "lat": 31.999741,
            "lng": 34.894775,
            "alt": 0,
            "dir": 302,
            "speed": 201,
            "v_speed": 2.1,
            "squawk": "4303",
            "flight_number": "90",
            "flight_icao": "UAL90",
            "flight_iata": "UA90",
            "dep_icao": "KEWR",
            "dep_iata": "EWR",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "UAL",
            "airline_iata": "UA",
            "aircraft_icao": "B78X",
            "updated": 1675952457,
            "status": "en-route"
        },
        {
            "hex": "A2F200",
            "reg_number": "N28912",
            "flag": "US",
            "lat": 32.251995,
            "lng": 34.676048,
            "alt": 1737,
            "dir": 126,
            "speed": 464,
            "squawk": "5222",
            "flight_number": "72",
            "flight_icao": "UAL72",
            "flight_iata": "UA72",
            "dep_icao": "KIAD",
            "dep_iata": "IAD",
            "arr_icao": "LLBG",
            "arr_iata": "TLV",
            "airline_icao": "UAL",
            "airline_iata": "UA",
            "aircraft_icao": "B788",
            "updated": 1675952456,
            "status": "en-route"
        },
        {
            "hex": "ADFECE",
            "reg_number": "84-00488",
            "lat": 29.732986,
            "lng": 34.228539,
            "alt": 5783,
            "dir": 178,
            "speed": 383,
            "squawk": "3303",
            "flight_number": "692",
            "flight_icao": "MFO692",
            "airline_icao": "MFO",
            "aircraft_icao": "BE20",
            "updated": 1675952456,
            "status": "en-route"
        }
    ],
    "terms": "Unauthorized access is prohibited and punishable by law. \nReselling data 'As Is' without AirLabs.Co permission is strictly prohibited. \nFull terms on https://airlabs.co/. \nContact us info@airlabs.co"
}
]